export enum ApiResources {
  ANSWER_BUNDLES = 'answer-bundles',
  AUTHENTICATION = 'authentication',
  EMAIL_TEMPLATES = 'email-templates',
  EMAILS = 'emails',
  NOTIFICATIONS = 'notifications',
  ONE_TIME_CODES = 'one-time-codes',
  PERMISSIONS = 'permissions',
  QUESTION_BUNDLES = 'question-bundles',
  QUESTIONS = 'questions',
  ROLES = 'roles',
  TOKENS = 'tokens',
  USER_GROUPS = 'user-groups',
  USERS = 'users',
}
