export enum LoginStatus {
  NEW = 'NEW',
  PASSWORD_RESET_PENDING = 'PASSWORD_RESET_PENDING',
  PASSWORD_RESET_IN_PROGRESS = 'PASSWORD_RESET_IN_PROGRESS',
  PENDING_LOGIN = 'PENDING_LOGIN',
  SUCCESSFUL = 'SUCCESSFUL',
}
